### ISSUE TITLE
Fix KAFKA job post bug

### ISSUE THREAD

**Issue by enochappiah** [jhu-oose-f24/Team-JobJays#145]
There is a bug when publishing a jobPost that causes the frontend to lag and the backend connection to throw "disconnect errors". This doesn't stop the program or app from running but there is usually a redirect after a job post is made, but because of the bug in the KAFKA publishing, the backend doesn't send the response soon enough and the redirect takes a long time to happen and once it finally sends the user may be on a different page which causes the redirect to happen late, disturbing user experience. 

If you cannot fix this in the Kafka or cannot disable the publishJobPost code, then we can just comment out the redirect but this is a last resort.

The error can be found in backend/../service/JobPostService.java : line 44:     "jobPostPublisherService.publishJobPost(newJobPostEntity);"

**Comment by muradazimzada** [comment]
This happens when logfile for KAFKA Server has lags, conflicts. Should not happen in Production
