### ISSUE TITLE
Frontend Integration for Resume

### ISSUE THREAD

**Issue by ahashi1263** [jhu-oose-f24/Team-JobJays#152]

**Comment by enochappiah** [comment]
resume should be in Applicant Profile class

**Comment by muradazimzada** [comment]
@luojiaxuan ?

**Comment by luojiaxuan** [comment]
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/bb050d5d-96d9-4134-83d2-b820b08b1289" />
sorry for not checking the project notification.
I have finished it some days ago.

**Comment by muradazimzada** [comment]
Thank you, @luojiaxuan!
